# netlify.toml
[build]
  publish = "."
  # No build command needed for a static site + functions

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["stripe"]

[build.environment]
  NODE_VERSION = "18"
